name: Generate Documentation

# Запуск при каждом пуше в ветку main/master или вручную
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Запускаем Doxygen (он автоматически найдет ваш Doxyfile)
      - name: Run Doxygen
        uses: mattnotexist/doxygen-action@v1
        with:
          # Вы можете указать путь к вашему Doxyfile, если он лежит не в корне
          doxyfile-path: './Doxyfile' 

      # 3. (Опционально) Сохраняем готовую документацию как артефакт
      - name: Upload Artifacts
        uses: actions/artifacts-action@v1 # Обновленный официальный экшен для работы с артефактами
        with:
          name: doxygen-docs
          # Укажите папку, куда Doxygen складывает HTML (зависит от настроек в Doxyfile, обычно html или docs/html)
          path: docs/html/ 